const data = [
    {
        id: 1,
        title: "Easy approach to Python multithreading",
        slug: "python-multithreading",
        category: "python",
        category_title: "Python",
        img: "news1.png",
        date: "February 7, 2023",
        author: "Valentin Cavarec",
        ttr: "5min",
        shortdesc: "You can implement this simple approach in your Python projects in under 5 minutes.",
        difficulty: "Easy",
    },
    {
        id: 1,
        title: "Easy approach to Python multithreading",
        slug: "python-multithreading",
        category: "python",
        category_title: "Python",
        img: "news1.png",
        date: "February 7, 2023",
        author: "Valentin Cavarec",
        ttr: "5min",
        shortdesc: "You can implement this simple approach in your Python projects in under 5 minutes.",
        difficulty: "Easy",
    },
    {
        id: 1,
        title: "Easy approach to Python multithreading",
        slug: "python-multithreading",
        category: "python",
        category_title: "Python",
        img: "news1.png",
        date: "February 7, 2023",
        author: "Valentin Cavarec",
        ttr: "5min",
        shortdesc: "You can implement this simple approach in your Python projects in under 5 minutes.",
        difficulty: "Easy",
    },
    {
        id: 1,
        title: "Easy approach to Python multithreading",
        slug: "python-multithreading",
        category: "python",
        category_title: "Python",
        img: "news1.png",
        date: "February 7, 2023",
        author: "Valentin Cavarec",
        ttr: "5min",
        shortdesc: "You can implement this simple approach in your Python projects in under 5 minutes.",
        difficulty: "Easy",
    },
    {
        id: 1,
        title: "Easy approach to Python multithreading",
        slug: "python-multithreading",
        category: "python",
        category_title: "Python",
        img: "news1.png",
        date: "February 7, 2023",
        author: "Valentin Cavarec",
        ttr: "5min",
        shortdesc: "You can implement this simple approach in your Python projects in under 5 minutes.",
        difficulty: "Easy",
    },
    {
        id: 1,
        title: "Easy approach to Python multithreading",
        slug: "python-multithreading",
        category: "python",
        category_title: "Python",
        img: "news1.png",
        date: "February 7, 2023",
        author: "Valentin Cavarec",
        ttr: "5min",
        shortdesc: "You can implement this simple approach in your Python projects in under 5 minutes.",
        difficulty: "Easy",
    },
    {
        id: 1,
        title: "Easy approach to Python multithreading",
        slug: "python-multithreading",
        category: "python",
        category_title: "Python",
        img: "news1.png",
        date: "February 7, 2023",
        author: "Valentin Cavarec",
        ttr: "5min",
        shortdesc: "You can implement this simple approach in your Python projects in under 5 minutes.",
        difficulty: "Easy",
    },
    {
        id: 1,
        title: "Easy approach to Python multithreading",
        slug: "python-multithreading",
        category: "python",
        category_title: "Python",
        img: "news1.png",
        date: "February 7, 2023",
        author: "Valentin Cavarec",
        ttr: "5min",
        shortdesc: "You can implement this simple approach in your Python projects in under 5 minutes.",
        difficulty: "Easy",
    },
    {
        id: 2,
        title: "Life is as free as eagles, or is it just loneliness?",
        slug: "python-zzz",
        category: "z",
        img: "news2.png",
        authorTitle: "Joseph",
        author: "author.jpg",
        date: "25 April 2022",
        difficulty: "Easy",
    },
];
export default data;